package app.bighead.vpn;

import javax.swing.*;
import javax.swing.border.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.awt.datatransfer.DataFlavor;
import java.net.*;
import java.net.http.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.io.IOException;
import java.time.Duration;
import java.util.List;
import java.util.*;
import java.util.regex.Pattern;

public final class Main {
    static final Color BG=new Color(49,51,56), SIDEBAR=new Color(30,31,34), PANEL=new Color(43,45,49), INPUT=new Color(30,31,34), BLURPLE=new Color(88,101,242), GREEN=new Color(35,165,90), TEXT=new Color(242,243,245), MUTED=new Color(181,186,193);
    public static void main(String[] args){if(!ensureWindowsAdministrator())return;SwingUtilities.invokeLater(()->{theme();new Window().setVisible(true);});}
    static boolean ensureWindowsAdministrator(){if(!System.getProperty("os.name","").startsWith("Windows"))return true;try{var test="if ((New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) { exit 0 } else { exit 1 }";var check=new ProcessBuilder("powershell.exe","-NoProfile","-Command",test).start();if(check.waitFor()==0)return true;var executable=ProcessHandle.current().info().command().orElse("");if(executable.isBlank())return true;var escaped=executable.replace("'","''");var parent=Path.of(executable).toAbsolutePath().getParent().toString().replace("'","''");new ProcessBuilder("powershell.exe","-NoProfile","-WindowStyle","Hidden","-Command","Start-Process -FilePath '"+escaped+"' -WorkingDirectory '"+parent+"' -Verb RunAs").start();return false;}catch(Exception e){return true;}}
    private static void theme(){var f=new Font("Segoe UI",Font.PLAIN,14);UIManager.put("defaultFont",f);UIManager.put("Panel.background",BG);UIManager.put("Label.foreground",TEXT);UIManager.put("Button.background",BLURPLE);UIManager.put("Button.foreground",Color.WHITE);UIManager.put("Button.focusPainted",false);UIManager.put("TextField.background",INPUT);UIManager.put("TextField.foreground",TEXT);UIManager.put("TextField.caretForeground",TEXT);UIManager.put("List.background",PANEL);UIManager.put("List.foreground",MUTED);UIManager.put("List.selectionBackground",new Color(64,66,73));UIManager.put("List.selectionForeground",TEXT);UIManager.put("TextArea.background",INPUT);UIManager.put("TextArea.foreground",MUTED);UIManager.put("ScrollPane.border",new EmptyBorder(0,0,0,0));UIManager.put("CheckBox.background",PANEL);UIManager.put("CheckBox.foreground",TEXT);UIManager.put("OptionPane.background",PANEL);UIManager.put("OptionPane.messageForeground",TEXT);UIManager.put("OptionPane.foreground",TEXT);}

    static final class Window extends JFrame {
        final Settings settings=Settings.load(); final DefaultListModel<Profile> profiles=new DefaultListModel<>(); final DefaultComboBoxModel<Object> groups=new DefaultComboBoxModel<>(); final DefaultListModel<ProcessItem> running=new DefaultListModel<>(); final DefaultListModel<String> selected=new DefaultListModel<>();
        final JList<Profile> profilesList=new JList<>(profiles); final JList<ProcessItem> runningList=new JList<>(running); final JList<String> selectedList=new JList<>(selected);
        final JComboBox<Object> groupBox=new JComboBox<>(groups);
        final JLabel status=new JLabel("Отключено"),detail=new JLabel("Выберите сервер"),dot=new JLabel("●"),alert=new JLabel(); final JButton connect=new DiscordButton("Включить",true);
        final JCheckBox listener=new JCheckBox("Включить listener"); final JTextField address=new JTextField(),port=new JTextField(),filter=new JTextField(),manualProcess=new JTextField(); final JTextArea logs=new JTextArea();
        final SingBox engine=new SingBox(this::log,this::engineStopped); List<ProcessItem> allProcesses=List.of(); long startedAt;
        Window(){super("Big Head VPN");var logo=logo(512);setIconImages(List.of(logo,scale(logo,256),scale(logo,64),scale(logo,32),scale(logo,16)));var dialogIcon=new ImageIcon(scale(logo,64));UIManager.put("OptionPane.informationIcon",dialogIcon);UIManager.put("OptionPane.questionIcon",dialogIcon);UIManager.put("OptionPane.warningIcon",dialogIcon);UIManager.put("OptionPane.errorIcon",dialogIcon);setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);setMinimumSize(new Dimension(1000,650));setSize(1180,760);setLocationRelativeTo(null);groups.addElement("Все серверы");settings.groups.forEach(groups::addElement);for(var p:settings.processes)selected.addElement(p);listener.setSelected(settings.listenerEnabled);address.setText(settings.listenAddress);port.setText(Integer.toString(settings.listenPort));build();events();refreshProfileView();refreshProcesses();selectSaved();}
        void build(){var root=new JPanel(new BorderLayout());root.add(sidebar(),BorderLayout.WEST);var workspace=new JPanel(new BorderLayout());alert.setOpaque(true);alert.setBackground(new Color(218,55,60));alert.setForeground(Color.WHITE);alert.setFont(alert.getFont().deriveFont(Font.BOLD));alert.setBorder(new EmptyBorder(11,16,11,16));alert.setVisible(false);workspace.add(alert,BorderLayout.NORTH);var content=new JPanel(new GridLayout(1,2,18,0));content.setBorder(new EmptyBorder(24,26,24,26));content.add(left());content.add(right());workspace.add(content);root.add(workspace);setContentPane(root);decorate();}
        JPanel sidebar(){var p=new JPanel();p.setBackground(SIDEBAR);p.setPreferredSize(new Dimension(82,0));p.setLayout(new BoxLayout(p,BoxLayout.Y_AXIS));p.setBorder(new EmptyBorder(18,12,18,12));var logoLabel=new JLabel(new ImageIcon(scale(logo(512),58)),SwingConstants.CENTER);logoLabel.setMaximumSize(new Dimension(58,58));logoLabel.setPreferredSize(new Dimension(58,58));logoLabel.setAlignmentX(.5f);p.add(logoLabel);p.add(Box.createVerticalStrut(18));for(var symbol:List.of("⌂","⇄","⚙")){var x=new JLabel(symbol,SwingConstants.CENTER);x.setForeground(MUTED);x.setFont(x.getFont().deriveFont(22f));x.setMaximumSize(new Dimension(54,44));x.setAlignmentX(.5f);p.add(x);p.add(Box.createVerticalStrut(8));}return p;}
        Image logo(int size){try(var in=Main.class.getResourceAsStream("/assets/icon.png")){if(in==null)throw new IOException("logo resource missing");return javax.imageio.ImageIO.read(in).getScaledInstance(size,size,Image.SCALE_SMOOTH);}catch(IOException e){log("Logo: "+e);return new java.awt.image.BufferedImage(size,size,java.awt.image.BufferedImage.TYPE_INT_ARGB);}}
        Image scale(Image image,int size){return image.getScaledInstance(size,size,Image.SCALE_SMOOTH);}
        JPanel left(){var p=vertical();var title=new JLabel("Big Head VPN");title.setFont(title.getFont().deriveFont(Font.BOLD,27));p.add(title);p.add(muted("VLESS  •  Hysteria2  •  Windows"));p.add(Box.createVerticalStrut(15));var state=new DiscordCard(new BorderLayout(12,10));dot.setForeground(new Color(128,132,142));dot.setFont(dot.getFont().deriveFont(26f));status.setFont(status.getFont().deriveFont(Font.BOLD,21));var line=transparent(new BorderLayout(8,0));line.add(dot,BorderLayout.WEST);line.add(status);state.add(line,BorderLayout.NORTH);state.add(detail);connect.setPreferredSize(new Dimension(120,46));state.add(connect,BorderLayout.SOUTH);p.add(state);p.add(section("СЕРВЕРЫ И ПОДПИСКИ"));var servers=new DiscordCard(new BorderLayout(0,8));var groupLine=transparent(new BorderLayout(6,0));groupLine.add(groupBox);var groupActions=flow();groupActions.add(button("↻",this::refreshGroup));groupActions.add(button("Удалить группу",this::deleteGroup));groupLine.add(groupActions,BorderLayout.EAST);servers.add(groupLine,BorderLayout.NORTH);servers.add(new JScrollPane(profilesList));var buttons=flow();for(var b:List.of(button("Вставить ссылку",this::paste),button("Добавить",this::manualProfile),button("Удалить сервер",this::deleteProfile)))buttons.add(b);servers.add(buttons,BorderLayout.SOUTH);p.add(servers);p.add(section("ЛОКАЛЬНЫЙ PROXY"));var local=new DiscordCard(new BorderLayout(8,8));local.add(listener,BorderLayout.NORTH);var lp=transparent(new GridLayout(1,2,8,0));lp.add(address);lp.add(port);local.add(lp);local.add(muted("SOCKS5 + HTTP · 127.0.0.1 только для этого ПК"),BorderLayout.SOUTH);p.add(local);return p;}
        JPanel right(){var p=vertical();p.add(section("ПРОЦЕССЫ ЧЕРЕЗ VPN"));p.add(muted("Если список пуст, туннель работает для всей системы"));var card=new DiscordCard(new BorderLayout(8,9));var search=transparent(new BorderLayout(7,0));search.add(filter);search.add(button("Обновить",this::refreshProcesses),BorderLayout.EAST);card.add(search,BorderLayout.NORTH);var lists=transparent(new GridLayout(1,2,12,0));var a=verticalClear();a.add(muted("ЗАПУЩЕННЫЕ"));a.add(new JScrollPane(runningList));var b=verticalClear();b.add(muted("В VPN"));b.add(new JScrollPane(selectedList));lists.add(a);lists.add(b);card.add(lists);var actions=flow();actions.add(button("Добавить  →",this::addSelected));actions.add(button("←  Убрать",this::removeSelected));card.add(actions,BorderLayout.SOUTH);p.add(card);p.add(Box.createVerticalStrut(9));var add=transparent(new BorderLayout(7,0));add.add(manualProcess);add.add(button("Добавить .exe",this::addManualProcess),BorderLayout.EAST);p.add(add);p.add(section("ЖУРНАЛ"));logs.setEditable(false);logs.setLineWrap(true);logs.setRows(5);p.add(new JScrollPane(logs));return p;}
        void decorate(){var renderer=new DefaultListCellRenderer(){public Component getListCellRendererComponent(JList<?> l,Object v,int i,boolean s,boolean f){var c=(JLabel)super.getListCellRendererComponent(l,v,i,s,f);c.setBorder(new EmptyBorder(9,10,9,10));return c;}};profilesList.setCellRenderer(renderer);runningList.setCellRenderer(renderer);selectedList.setCellRenderer(renderer);for(var x:List.of(address,port,filter,manualProcess)){x.setBorder(new CompoundBorder(new LineBorder(INPUT),new EmptyBorder(9,10,9,10)));x.setPreferredSize(new Dimension(100,38));}}
        JPanel vertical(){var p=new JPanel();p.setLayout(new BoxLayout(p,BoxLayout.Y_AXIS));return p;} JPanel verticalClear(){var p=vertical();p.setOpaque(false);return p;} JPanel transparent(LayoutManager l){var p=new JPanel(l);p.setOpaque(false);return p;} JPanel flow(){return transparent(new FlowLayout(FlowLayout.LEFT,4,2));} JLabel muted(String text){var l=new JLabel("<html>"+text+"</html>");l.setForeground(MUTED);l.setBorder(new EmptyBorder(5,2,7,2));return l;} JLabel section(String text){var l=new JLabel(text);l.setForeground(MUTED);l.setFont(l.getFont().deriveFont(Font.BOLD,12));l.setBorder(new EmptyBorder(18,2,7,2));return l;} JButton button(String text,Runnable run){var b=new DiscordButton(text,false);b.addActionListener(e->run.run());return b;}
        void events(){connect.addActionListener(e->toggle());groupBox.addActionListener(e->refreshProfileView());profilesList.addListSelectionListener(e->{if(!e.getValueIsAdjusting()){var p=profilesList.getSelectedValue();settings.selectedId=p==null?"":p.id();save();render();}});filter.getDocument().addDocumentListener((SimpleDocumentListener)this::applyFilter);addWindowListener(new java.awt.event.WindowAdapter(){public void windowClosing(java.awt.event.WindowEvent e){engine.close();save();dispose();}});}
        void toggle(){if(engine.running()){connect.setEnabled(false);status.setText("Отключение…");Thread.ofVirtual().start(()->{engine.stop();startedAt=0;SwingUtilities.invokeLater(()->{connect.setEnabled(true);render();});});return;}var p=profilesList.getSelectedValue();if(p==null){error("Сначала добавьте и выберите сервер.");return;}if(!readListener())return;connect.setEnabled(false);status.setText("Подключение…");Thread.ofVirtual().start(()->{try{engine.start(p,settings);startedAt=System.currentTimeMillis();SwingUtilities.invokeLater(this::render);}catch(Exception ex){log(ex.getMessage());SwingUtilities.invokeLater(()->error(ex.getMessage()));}finally{SwingUtilities.invokeLater(()->connect.setEnabled(true));}});}
        void engineStopped(String reason){SwingUtilities.invokeLater(()->{startedAt=0;connect.setEnabled(true);render();if(reason!=null&&!reason.isBlank())error("VPN остановлен: "+reason);});}
        void render(){boolean on=engine.running();status.setText(on?"Подключено":"Отключено");dot.setForeground(on?GREEN:new Color(128,132,142));connect.setText(on?"Выключить":"Включить");var p=profilesList.getSelectedValue();detail.setText(p==null?"Выберите сервер":p.name()+(on?" · TUN активен":""));}
        void paste(){try{String text=null;Exception cause=null;for(int i=0;i<4&&text==null;i++)try{var cb=Toolkit.getDefaultToolkit().getSystemClipboard();if(!cb.isDataFlavorAvailable(DataFlavor.stringFlavor))throw new IllegalStateException("в буфере нет текста");text=(String)cb.getData(DataFlavor.stringFlavor);}catch(Exception e){cause=e;Thread.sleep(70);}if(text==null)throw cause;importText(text);}catch(Exception e){log("Clipboard error: "+e);error("Не удалось прочитать ссылку из буфера: "+e.getMessage());}}
        void manualProfile(){var area=new JTextArea(6,52);area.setLineWrap(true);area.setWrapStyleWord(true);area.setBorder(new EmptyBorder(10,10,10,10));var panel=vertical();panel.add(new JLabel("Вставьте VPN-ссылки или HTTPS-ссылку подписки (Ctrl+V):"));panel.add(Box.createVerticalStrut(8));panel.add(new JScrollPane(area));var paste=button("Вставить из буфера",area::paste);panel.add(paste);if(JOptionPane.showConfirmDialog(this,panel,"Добавить сервер",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE)==JOptionPane.OK_OPTION)importText(area.getText());}
        void importText(String text){var uris=extractUris(text);if(!uris.isEmpty()){addProfiles(uris,"");return;}var m=Pattern.compile("(?i)https?://[^\\s<>\\\"']+").matcher(text.trim());if(!m.find()){error("Не найдены VPN-ссылки или HTTPS-ссылка подписки");return;}var url=m.group().replaceAll("[),.;]+$","");var existing=settings.groups.stream().filter(g->g.url().equals(url)).findFirst().orElse(null);fetchSubscription(url,existing);}
        void fetchSubscription(String url,SubscriptionGroup existing){clearError();status.setText(existing==null?"Добавление подписки…":"Обновление подписки…");connect.setEnabled(false);log("Загрузка подписки: "+URI.create(url).getHost());Thread.ofVirtual().start(()->{try{var request=HttpRequest.newBuilder(URI.create(url)).timeout(Duration.ofSeconds(20)).header("User-Agent","BigHeadVPN/0.1").GET().build();var client=HttpClient.newBuilder().followRedirects(HttpClient.Redirect.NORMAL).connectTimeout(Duration.ofSeconds(12)).build();var response=client.send(request,HttpResponse.BodyHandlers.ofByteArray());log("Подписка HTTP "+response.statusCode()+", "+response.body().length+" байт");if(response.statusCode()<200||response.statusCode()>299)throw new IllegalStateException("HTTP "+response.statusCode());if(response.body().length>2_000_000)throw new IllegalStateException("ответ больше 2 МБ");var body=new String(response.body(),StandardCharsets.UTF_8);var found=extractUris(body);if(found.isEmpty())try{body=new String(Base64.getMimeDecoder().decode(body.trim()),StandardCharsets.UTF_8);found=extractUris(body);}catch(IllegalArgumentException ignored){}if(found.isEmpty())throw new IllegalStateException("серверы в ответе не найдены");var name=subscriptionName(body,url);var result=List.copyOf(found);SwingUtilities.invokeLater(()->applySubscription(existing,name,url,result));}catch(Exception e){log("Subscription error: "+e);SwingUtilities.invokeLater(()->error("Не удалось загрузить подписку: "+e.getClass().getSimpleName()+": "+e.getMessage()));}finally{SwingUtilities.invokeLater(()->{connect.setEnabled(true);render();});}});}
        String subscriptionName(String body,String url){var m=Pattern.compile("(?im)^#profile-title:\\s*(.+)$").matcher(body);if(m.find()&&!m.group(1).isBlank())return m.group(1).trim();try{return URI.create(url).getHost();}catch(Exception e){return "Подписка";}}
        void applySubscription(SubscriptionGroup existing,String name,String url,List<String> values){var group=existing==null?new SubscriptionGroup(name,url):new SubscriptionGroup(existing.id(),name,url);var parsed=new ArrayList<Profile>();var errors=new LinkedHashSet<String>();for(var value:values)try{var p=ProfileParser.parse(value);ProfileParser.outbound(p);parsed.add(p.inGroup(group.id()));}catch(Exception e){errors.add(e.getMessage());}if(parsed.isEmpty()){error("В подписке нет поддерживаемых серверов");return;}if(existing==null){settings.groups.add(group);groups.addElement(group);}else{var index=settings.groups.indexOf(existing);if(index>=0)settings.groups.set(index,group);for(int i=1;i<groups.getSize();i++)if(groups.getElementAt(i) instanceof SubscriptionGroup g&&g.id().equals(group.id()))groups.removeElementAt(i--);}settings.profiles.removeIf(p->p.groupId().equals(group.id()));settings.profiles.addAll(parsed);if(existing!=null)groups.addElement(group);groupBox.setSelectedItem(group);save();refreshProfileView();selectSaved();log((existing==null?"Добавлена":"Обновлена")+" подписка '"+name+"': "+parsed.size()+" серверов");if(!errors.isEmpty())warning("Добавлено серверов: "+parsed.size()+". Часть серверов пропущена:\n"+String.join("\n",errors));}
        List<String> extractUris(String text){var result=new ArrayList<String>();var m=Pattern.compile("(?i)(?:vless|hysteria2?|hy2)://[^\\s<>\\\"']+").matcher(text);while(m.find())result.add(m.group().replaceAll("[),.;]+$",""));return result;}
        void addProfiles(Collection<String> values,String groupId){if(values.isEmpty()){error("В буфере не найдены ссылки vless://, hysteria://, hysteria2:// или hy2://");return;}var errors=new LinkedHashSet<String>();int count=0;for(var value:values)try{var p=ProfileParser.parse(value).inGroup(groupId);ProfileParser.outbound(p);if(settings.profiles.stream().noneMatch(x->x.uri().equals(p.uri()))){settings.profiles.add(p);count++;}}catch(Exception e){errors.add(e.getMessage());}refreshProfileView();if(profilesList.getSelectedIndex()<0&&profiles.size()>0)profilesList.setSelectedIndex(0);save();log("Импортировано серверов: "+count);if(!errors.isEmpty())warning("Добавлено серверов: "+count+". Часть серверов пропущена:\n"+String.join("\n",errors));}
        void refreshProfileView(){if(profiles==null)return;var chosen=groupBox.getSelectedItem();var selectedId=settings.selectedId;profiles.clear();settings.profiles.stream().filter(p->!(chosen instanceof SubscriptionGroup g)||p.groupId().equals(g.id())).forEach(profiles::addElement);for(int i=0;i<profiles.size();i++)if(profiles.get(i).id().equals(selectedId)){profilesList.setSelectedIndex(i);break;}render();}
        void refreshGroup(){if(groupBox.getSelectedItem() instanceof SubscriptionGroup g)fetchSubscription(g.url(),g);else error("Выберите группу подписки");}
        void deleteGroup(){if(!(groupBox.getSelectedItem() instanceof SubscriptionGroup g)){error("Выберите группу подписки");return;}if(engine.running()){error("Сначала отключите VPN.");return;}if(JOptionPane.showConfirmDialog(this,"Удалить группу '"+g.name()+"' и все её серверы?","Удаление подписки",JOptionPane.YES_NO_OPTION)!=JOptionPane.YES_OPTION)return;settings.profiles.removeIf(p->p.groupId().equals(g.id()));settings.groups.removeIf(x->x.id().equals(g.id()));groups.removeElement(g);groupBox.setSelectedIndex(0);save();refreshProfileView();}
        void deleteProfile(){var p=profilesList.getSelectedValue();if(p==null)return;if(engine.running()){error("Сначала отключите VPN.");return;}settings.profiles.remove(p);profiles.removeElement(p);if(!profiles.isEmpty())profilesList.setSelectedIndex(0);save();}
        void selectSaved(){for(int i=0;i<profiles.size();i++)if(profiles.get(i).id().equals(settings.selectedId)){profilesList.setSelectedIndex(i);return;}if(!profiles.isEmpty())profilesList.setSelectedIndex(0);render();}
        void refreshProcesses(){allProcesses=ProcessHandle.allProcesses().map(h->{var info=h.info();var command=info.command().orElse("process-"+h.pid());var name=Path.of(command).getFileName().toString();if(!name.toLowerCase(Locale.ROOT).endsWith(".exe")&&System.getProperty("os.name").startsWith("Windows"))name += ".exe";return new ProcessItem(h.pid(),name,command);}).sorted(Comparator.comparing(ProcessItem::name,String.CASE_INSENSITIVE_ORDER)).toList();applyFilter();}
        void applyFilter(){var q=filter.getText().trim();running.clear();allProcesses.stream().filter(x->q.isEmpty()||x.name().toLowerCase(Locale.ROOT).contains(q.toLowerCase(Locale.ROOT))).forEach(running::addElement);}
        void addSelected(){for(var p:runningList.getSelectedValuesList())addName(p.name());saveProcesses();}void removeSelected(){for(var n:selectedList.getSelectedValuesList())selected.removeElement(n);saveProcesses();}
        void addManualProcess(){var n=manualProcess.getText().trim();if(n.isEmpty())return;if(!n.toLowerCase(Locale.ROOT).endsWith(".exe"))n += ".exe";addName(n);manualProcess.setText("");saveProcesses();}void addName(String n){for(int i=0;i<selected.size();i++)if(selected.get(i).equalsIgnoreCase(n))return;selected.addElement(n);}void saveProcesses(){settings.processes.clear();for(int i=0;i<selected.size();i++)settings.processes.add(selected.get(i));save();}
        boolean readListener(){try{InetAddress.getByName(address.getText().trim());int n=Integer.parseInt(port.getText().trim());if(n<1||n>65535)throw new Exception();settings.listenerEnabled=listener.isSelected();settings.listenAddress=address.getText().trim();settings.listenPort=n;save();return true;}catch(Exception e){error("Укажите корректные IP и порт (1–65535).");return false;}}
        void save(){settings.save();}void clearError(){alert.setVisible(false);alert.setText("");}JLabel dialogMessage(String s){var label=new JLabel("<html><div style='width:360px'>"+escape(s).replace("\n","<br>")+"</div></html>");label.setForeground(TEXT);label.setFont(label.getFont().deriveFont(14f));return label;}String escape(String s){return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;");}void warning(String s){alert.setBackground(new Color(240,178,50));alert.setForeground(SIDEBAR);alert.setText("Предупреждение: "+s.replace("\n"," · "));alert.setVisible(true);JOptionPane.showMessageDialog(this,dialogMessage(s),"Big Head VPN — предупреждение",JOptionPane.WARNING_MESSAGE);}void error(String s){alert.setBackground(new Color(218,55,60));alert.setForeground(Color.WHITE);alert.setText("Ошибка: "+s.replace("\n"," · "));alert.setVisible(true);JOptionPane.showMessageDialog(this,dialogMessage(s),"Big Head VPN — ошибка",JOptionPane.ERROR_MESSAGE);render();}void log(String s){if(s==null)return;SwingUtilities.invokeLater(()->{logs.append(s+"\n");logs.setCaretPosition(logs.getDocument().getLength());});}
    }
    static final class DiscordCard extends JPanel {DiscordCard(LayoutManager l){super(l);setBackground(PANEL);setBorder(new EmptyBorder(14,14,14,14));}}
    static final class DiscordButton extends JButton {final boolean primary;DiscordButton(String text,boolean primary){super(text);this.primary=primary;setOpaque(false);setContentAreaFilled(false);setBorder(new EmptyBorder(10,14,10,14));setForeground(Color.WHITE);setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));}protected void paintComponent(Graphics g){var g2=(Graphics2D)g.create();g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);g2.setColor(primary?BLURPLE:(getModel().isRollover()?new Color(78,80,88):new Color(64,66,73)));g2.fillRoundRect(0,0,getWidth(),getHeight(),8,8);g2.dispose();super.paintComponent(g);}}
    record ProcessItem(long pid,String name,String path){@Override public String toString(){return name+"  ·  PID "+pid;}}
    interface SimpleDocumentListener extends DocumentListener {void update();default void insertUpdate(DocumentEvent e){update();}default void removeUpdate(DocumentEvent e){update();}default void changedUpdate(DocumentEvent e){update();}}
}
