package app.bighead.vpn;

import java.io.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.function.Consumer;

public final class SingBox implements AutoCloseable {
    private volatile Process process; private final Consumer<String> log; private final Consumer<String> stopped; private volatile boolean stopping; private volatile String lastLine="";
    public SingBox(Consumer<String> log,Consumer<String> stopped){this.log=log;this.stopped=stopped;} public boolean running(){return process!=null&&process.isAlive();}
    public synchronized void start(Profile profile,Settings s)throws Exception{if(running())return;var exe=findExecutable();Files.createDirectories(Settings.DIR);var tunMode=!Settings.MODE_PROXY.equals(s.mode);var physicalInterface=tunMode?defaultWindowsInterface():"";var endpointRoutes=tunMode?resolveEndpointRoutes(profile):List.<String>of();var config=Settings.DIR.resolve("config.json");Files.writeString(config,config(profile,s,physicalInterface,endpointRoutes),StandardCharsets.UTF_8);log.accept(tunMode?"Режим: VPN для всей системы через TUN":"Режим: прокси-сервер SOCKS5 + HTTP на "+s.listenAddress+":"+s.listenPort);if(tunMode&&!physicalInterface.isBlank())log.accept("Защита от петли: исходящие соединения привязаны к "+physicalInterface);else if(tunMode)log.accept("Защита от петли: автоматическое определение физического интерфейса");if(!endpointRoutes.isEmpty())log.accept("Адрес VPN-сервера исключён из маршрута TUN: "+String.join(", ",endpointRoutes));
        var check=new ProcessBuilder(exe.toString(),"check","-c",config.toString()).redirectErrorStream(true).start();if(!check.waitFor(8,java.util.concurrent.TimeUnit.SECONDS)){check.destroyForcibly();throw new IOException("Проверка конфигурации sing-box превысила 8 секунд");}var error=new String(check.getInputStream().readAllBytes(),StandardCharsets.UTF_8);if(check.exitValue()!=0)throw new IOException("Ошибка конфигурации sing-box:\n"+cleanLog(error));
        stopping=false;lastLine="";var started=new ProcessBuilder(exe.toString(),"run","-c",config.toString()).redirectErrorStream(true).start();process=started;
        Thread.ofVirtual().start(()->{try(var r=new BufferedReader(new InputStreamReader(started.getInputStream(),StandardCharsets.UTF_8))){r.lines().forEach(line->{var clean=cleanLog(line);lastLine=clean;log.accept(clean);});}catch(IOException ignored){}finally{var unexpected=process==started&&!stopping;if(process==started)process=null;if(unexpected)stopped.accept(lastLine.isBlank()?"Сетевое ядро неожиданно завершилось":lastLine);}});
        Thread.sleep(800);if(!started.isAlive())throw new IOException("sing-box не запустился: "+(lastLine.isBlank()?"неизвестная ошибка":lastLine));if((Settings.MODE_PROXY.equals(s.mode)||s.listenerEnabled)&&!waitForListener(s.listenAddress,s.listenPort,2500)){stop();throw new IOException("Прокси-сервер не открыл "+s.listenAddress+":"+s.listenPort+". Возможно, порт уже занят или заблокирован брандмауэром.");}}
    public synchronized void stop(){var target=process;if(target==null)return;stopping=true;long pid=target.pid();target.descendants().forEach(h->{try{h.destroy();}catch(Exception ignored){}});target.destroy();try{if(!target.waitFor(1200,java.util.concurrent.TimeUnit.MILLISECONDS)){target.descendants().forEach(h->{try{h.destroyForcibly();}catch(Exception ignored){}});target.destroyForcibly();target.waitFor(800,java.util.concurrent.TimeUnit.MILLISECONDS);}if(target.isAlive()&&System.getProperty("os.name","").startsWith("Windows")){var killer=new ProcessBuilder("taskkill","/PID",Long.toString(pid),"/T","/F").redirectErrorStream(true).start();if(!killer.waitFor(1500,java.util.concurrent.TimeUnit.MILLISECONDS))killer.destroyForcibly();}}catch(Exception e){log.accept("Ошибка остановки: "+e.getMessage());}finally{if(process==target)process=null;stopping=false;stopped.accept("");}} public void close(){stop();}
    private static Path findExecutable()throws FileNotFoundException{for(var p:List.of(Path.of("tools","sing-box.exe"),Path.of(System.getProperty("java.home")).getParent().resolve("tools").resolve("sing-box.exe")))if(Files.exists(p))return p.toAbsolutePath();throw new FileNotFoundException("Не найден tools\\sing-box.exe. Запустите scripts\\download-sing-box.ps1");}
    static String cleanLog(String value){if(value==null)return "";return value.replaceAll("\\u001B\\[[0-?]*[ -/]*[@-~]","").replaceAll("[\\p{Cc}&&[^\\r\\n\\t]]","").trim();}
    static String config(Profile p,Settings s){return config(p,s,"",List.of());}
    static String config(Profile p,Settings s,String physicalInterface,List<String> endpointRoutes){var proxyMode=Settings.MODE_PROXY.equals(s.mode);var tun=Json.object("type","tun","tag","tun-in","interface_name","BigHeadVPN","address",List.of("172.19.0.1/30"),"mtu",1400,"auto_route",true,"strict_route",true,"route_exclude_address",endpointRoutes.isEmpty()?null:endpointRoutes,"stack","mixed");var ins=new ArrayList<String>();if(!proxyMode)ins.add(tun);if(proxyMode||s.listenerEnabled)ins.add(Json.object("type","mixed","tag","local-proxy","listen",s.listenAddress,"listen_port",s.listenPort));
        var rules=new ArrayList<String>();if(proxyMode||s.listenerEnabled)rules.add(Json.object("inbound",List.of("local-proxy"),"action","route","outbound","proxy"));
        var bind=physicalInterface.isBlank()?null:physicalInterface;return Json.object("log",Json.raw(Json.object("level","warn","timestamp",true)),"inbounds",Json.raw("["+String.join(",",ins)+"]"),"outbounds",Json.raw("["+ProfileParser.outbound(p,physicalInterface)+","+Json.object("type","direct","tag","direct","bind_interface",bind)+"]"),"route",Json.raw(Json.object("auto_detect_interface",!proxyMode,"rules",Json.raw("["+String.join(",",rules)+"]"),"final","proxy")));}
    static List<String> resolveEndpointRoutes(Profile profile){var routes=new LinkedHashSet<String>();try{for(var address:java.net.InetAddress.getAllByName(ProfileParser.serverHost(profile))){var host=address.getHostAddress();var zone=host.indexOf('%');if(zone>=0)host=host.substring(0,zone);routes.add(host+(address instanceof java.net.Inet4Address?"/32":"/128"));}}catch(Exception ignored){}return List.copyOf(routes);}
    static boolean waitForListener(String address,int port,long timeoutMillis){var target=switch(address){case "0.0.0.0"->"127.0.0.1";case "::","[::]"->"::1";default->address;};var deadline=System.nanoTime()+java.util.concurrent.TimeUnit.MILLISECONDS.toNanos(timeoutMillis);while(System.nanoTime()<deadline){try(var socket=new java.net.Socket()){socket.connect(new java.net.InetSocketAddress(target,port),250);socket.setSoTimeout(400);socket.getOutputStream().write(new byte[]{5,1,0});var reply=socket.getInputStream().readNBytes(2);return reply.length==2&&reply[0]==5&&reply[1]==0;}catch(IOException ignored){try{Thread.sleep(80);}catch(InterruptedException e){Thread.currentThread().interrupt();return false;}}}return false;}
    static String defaultWindowsInterface(){if(!System.getProperty("os.name","").startsWith("Windows"))return "";Process process=null;try{var command="[Console]::OutputEncoding=[Text.UTF8Encoding]::new(); Get-NetIPConfiguration | Where-Object IPv4DefaultGateway | Sort-Object { $_.NetIPv4Interface.InterfaceMetric } | Select-Object -First 1 -ExpandProperty InterfaceAlias";process=new ProcessBuilder("powershell.exe","-NoProfile","-NonInteractive","-Command",command).redirectErrorStream(true).start();if(!process.waitFor(4,java.util.concurrent.TimeUnit.SECONDS)){process.destroyForcibly();return "";}if(process.exitValue()!=0)return "";return new String(process.getInputStream().readAllBytes(),StandardCharsets.UTF_8).trim();}catch(Exception ignored){if(process!=null)process.destroyForcibly();return "";}}
}
